import type { Metadata } from "next";
import { Geist, Geist_Mono, Lobster } from "next/font/google";
import "./globals.css";
import Store from "./StoreProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  preload: false,
});

const lobster = Lobster({
  variable: "--font-lobster",
  subsets: ["latin"],
  weight: "400",
  preload: false,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: false,
});

export const metadata: Metadata = {
  title: "Cake Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${lobster.variable} h-full antialiased flex flex-col items-center`}
    >
      <body className="min-h-full flex flex-col items-center max-w-7xl bg-[#FFF8F3]/90 text-gray-900  dark:bg-gray-800 dark:text-gray-50 w-full">
        <Store>{children}</Store>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
